//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMPG223_Group22_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANIMAL
    {
        public int Animal_ID { get; set; }
        public string Animal_Name { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<bool> Vaccination { get; set; }
    }
}
