//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMPG223_Group22_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANIMAL> ANIMALS { get; set; }
        public virtual DbSet<TICKET> TICKETS { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VISITOR> VISITORS { get; set; }
        public virtual DbSet<VISITORS_ON_TICKET> VISITORS_ON_TICKET { get; set; }
    }
}
