//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMPG223_Group22_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        public int Ticket_ID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> isTicketValid { get; set; }
    
        public virtual VISITORS_ON_TICKET VISITORS_ON_TICKET { get; set; }
    }
}
